#!/usr/bin/env python3

from pathlib import Path


# Files commonly generated by desktop filesystems that must not affect
# script-role or boundary validation outcomes.
_METADATA_FILENAMES = {
    ".DS_Store",
    "Thumbs.db",
    "desktop.ini",
}


def is_metadata_file(path: Path) -> bool:
    name = path.name
    return name.startswith("._") or name in _METADATA_FILENAMES

