#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONTRACT_PATH="$ROOT_DIR/contracts/federated-ci-summary-contract.md"
CONTRACTS_README="$ROOT_DIR/contracts/README.md"

python3 - <<'PY' "$CONTRACT_PATH" "$CONTRACTS_README"
import sys
from pathlib import Path

contract = Path(sys.argv[1]).read_text(encoding="utf-8")
contracts_readme = Path(sys.argv[2]).read_text(encoding="utf-8")

required_contract_snippets = [
    "planningops/artifacts/ci/federated-ci-summary.json",
    "planningops/artifacts/validation/federated-ci-summary-validation.json",
    "planningops/artifacts/validation/federated-ci-summary-readiness.json",
    "planningops/artifacts/validation/federated-ci-summary-readiness-validation.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-validation.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-validation.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-validation.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-validation.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-validation.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-validation.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-validation.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-validation.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status-validation.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status-bundle.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status-bundle-validation.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-validation.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-validation.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-validation.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-validation.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-validation.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle.json",
    "planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-validation.json",
    "planningops/scripts/federation/federated_ci_summary.py",
    "planningops/scripts/federation/reconcile_federated_ci_summary_tmp.py",
    "planningops/scripts/validate_federated_ci_summary_tmp_reconcile.py",
    "planningops/scripts/resolve_federated_ci_summary_tmp_reconcile.py",
    "planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle.py",
    "planningops/scripts/doctor_federated_ci_summary_tmp_reconcile_bundle.py",
    "planningops/scripts/gate_federated_ci_summary_tmp_reconcile_bundle.sh",
    "planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status.py",
    "planningops/scripts/resolve_federated_ci_summary_tmp_reconcile_bundle_status.py",
    "planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle.py",
    "planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_validation_contract.sh",
    "planningops/scripts/doctor_federated_ci_summary_tmp_reconcile_bundle_status_bundle.py",
    "planningops/scripts/gate_federated_ci_summary_tmp_reconcile_bundle_status_bundle.sh",
    "planningops/scripts/test_doctor_federated_ci_summary_tmp_reconcile_bundle_status_bundle.sh",
    "planningops/scripts/test_gate_federated_ci_summary_tmp_reconcile_bundle_status_bundle.sh",
    "planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status.py",
    "planningops/scripts/resolve_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status.py",
    "planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle.py",
    "planningops/scripts/doctor_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle.py",
    "planningops/scripts/gate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status.py",
    "planningops/scripts/resolve_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status.py",
    "planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle.py",
    "planningops/scripts/doctor_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle.py",
    "planningops/scripts/gate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status.py",
    "planningops/scripts/resolve_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status.py",
    "planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle.py",
    "planningops/scripts/doctor_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle.py",
    "planningops/scripts/gate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/resolve_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status.py",
    "planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.py",
    "planningops/scripts/doctor_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.py",
    "planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status.py",
    "planningops/scripts/gate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/resolve_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status.py",
    "planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status.py",
    "planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.py",
    "planningops/scripts/doctor_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.py",
    "planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status.py",
    "planningops/scripts/gate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/resolve_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status.py",
    "planningops/scripts/resolve_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status.py",
    "planningops/scripts/doctor_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.py",
    "planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status.py",
    "planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.py",
    "planningops/scripts/gate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_contract.sh",
    "planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_validation_contract.sh",
    "planningops/scripts/test_resolve_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status.sh",
    "planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_validation_contract.sh",
    "planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_contract.sh",
    "planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_validation_contract.sh",
    "planningops/scripts/test_doctor_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/test_gate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/test_resolve_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status.sh",
    "planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_validation_contract.sh",
    "planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_contract.sh",
    "planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_validation_contract.sh",
    "planningops/scripts/test_doctor_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/test_gate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/test_resolve_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status.sh",
    "planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_validation_contract.sh",
    "planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_contract.sh",
    "planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_validation_contract.sh",
    "planningops/scripts/test_doctor_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/test_gate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/test_resolve_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status.sh",
    "planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_validation_contract.sh",
    "planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_contract.sh",
    "planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_validation_contract.sh",
    "planningops/scripts/test_doctor_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/test_gate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/test_resolve_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status.sh",
    "planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_validation_contract.sh",
    "planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_contract.sh",
    "planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_validation_contract.sh",
    "planningops/scripts/test_doctor_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/test_gate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/test_resolve_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status.sh",
    "planningops/scripts/test_resolve_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status.sh",
    "planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_validation_contract.sh",
    "planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_validation_contract.sh",
    "planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_contract.sh",
    "planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_validation_contract.sh",
    "planningops/scripts/test_doctor_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/test_gate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_validation_contract.sh",
    "planningops/scripts/doctor_federated_ci_summary_tmp_reconcile.py",
    "planningops/scripts/gate_federated_ci_summary_tmp_reconcile.sh",
    "planningops/scripts/test_cross_repo_conformance_run_root_reuse_contract.sh",
    "planningops/scripts/autonomous_supervisor_loop.py",
    ".github/workflows/federated-ci-matrix.yml",
    "planningops/contracts/supervisor-operator-handoff-contract.md",
    "python3 planningops/scripts/assess_federated_ci_summary_readiness.py --strict",
    "python3 planningops/scripts/resolve_federated_ci_summary_tmp_reconcile.py --artifact-file planningops/artifacts/validation/federated-ci-summary-tmp-reconcile.json",
    "python3 planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle.py --bundle-file planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle.json --strict",
    "python3 planningops/scripts/doctor_federated_ci_summary_tmp_reconcile_bundle.py --require-pass",
    "python3 planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status.py --strict",
    "python3 planningops/scripts/resolve_federated_ci_summary_tmp_reconcile_bundle_status.py --artifact-file planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status.json",
    "python3 planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle.py --bundle-file planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle.json --strict",
    "bash planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_validation_contract.sh",
    "python3 planningops/scripts/doctor_federated_ci_summary_tmp_reconcile_bundle_status_bundle.py --require-pass",
    "python3 planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status.py --strict",
    "python3 planningops/scripts/resolve_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status.py --artifact-file planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status.json",
    "python3 planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle.py --bundle-file planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle.json --strict",
    "python3 planningops/scripts/doctor_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle.py --require-pass",
    "python3 planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status.py --strict",
    "python3 planningops/scripts/resolve_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status.py --artifact-file planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status.json",
    "python3 planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle.py --bundle-file planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle.json --strict",
    "python3 planningops/scripts/doctor_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle.py --require-pass",
    "python3 planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status.py --strict",
    "bash planningops/scripts/gate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle.sh",
    "python3 planningops/scripts/resolve_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status.py --artifact-file planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status.json",
    "python3 planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle.py --bundle-file planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status-bundle.json --strict",
    "python3 planningops/scripts/doctor_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle.py --require-pass",
    "python3 planningops/scripts/resolve_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status.py --artifact-file planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status.json",
    "python3 planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.py --bundle-file planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle.json --strict",
    "python3 planningops/scripts/doctor_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.py --require-pass",
    "python3 planningops/scripts/resolve_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status.py --artifact-file planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status.json",
    "python3 planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.py --bundle-file planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle.json --strict",
    "python3 planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status.py --strict",
    "bash planningops/scripts/gate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.sh",
    "python3 planningops/scripts/doctor_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.py --require-pass",
    "python3 planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status.py --strict",
    "bash planningops/scripts/gate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.sh",
    "python3 planningops/scripts/resolve_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status.py --artifact-file planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status.json",
    "python3 planningops/scripts/resolve_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status.py --artifact-file planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status.json",
    "python3 planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.py --bundle-file planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle.json --strict",
    "python3 planningops/scripts/doctor_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.py --require-pass",
    "python3 planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status.py --strict",
    "python3 planningops/scripts/validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.py --bundle-file planningops/artifacts/validation/federated-ci-summary-tmp-reconcile-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle.json --strict",
    "bash planningops/scripts/gate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.sh",
    "bash planningops/scripts/gate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_bundle_status_bundle.sh",
    "bash planningops/scripts/gate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle.sh",
    "bash planningops/scripts/gate_federated_ci_summary_tmp_reconcile_bundle_status_bundle.sh",
    "bash planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_contract.sh",
    "bash planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_validation_contract.sh",
    "bash planningops/scripts/test_resolve_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status.sh",
    "bash planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_validation_contract.sh",
    "bash planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_contract.sh",
    "bash planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle_status_validation_contract.sh",
    "bash planningops/scripts/test_doctor_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle.sh",
    "bash planningops/scripts/test_gate_federated_ci_summary_tmp_reconcile_bundle_status_bundle_status_bundle.sh",
    "bash planningops/scripts/test_validate_federated_ci_summary_tmp_reconcile_bundle_status_validation_contract.sh",
    "bash planningops/scripts/gate_federated_ci_summary_tmp_reconcile_bundle.sh",
    "python3 planningops/scripts/doctor_federated_ci_summary_tmp_reconcile.py --require-pass",
    "bash planningops/scripts/gate_federated_ci_summary_tmp_reconcile.sh",
    "python3 planningops/scripts/doctor_federated_ci_summary.py --require-pass",
    "bash planningops/scripts/gate_federated_ci_summary.sh",
    "status=degraded",
]

for snippet in required_contract_snippets:
    assert snippet in contract, f"missing contract snippet: {snippet}"

assert "federated-ci-summary-contract.md" in contracts_readme, "contracts README missing federated CI summary contract"
PY

echo "federated ci summary contract doc ok"
