#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONTRACT_PATH="$ROOT_DIR/contracts/plain-python-compat-manifest-contract.md"
CONTRACTS_README="$ROOT_DIR/contracts/README.md"

python3 - <<'PY' "$CONTRACT_PATH" "$CONTRACTS_README"
import sys
from pathlib import Path

contract = Path(sys.argv[1]).read_text(encoding="utf-8")
contracts_readme = Path(sys.argv[2]).read_text(encoding="utf-8")

required_contract_snippets = [
    "planningops/config/plain-python-compat-manifest.json",
    "planningops/schemas/plain-python-compat-manifest.schema.json",
    "planningops/schemas/plain-python-compat-manifest-validation.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status-bundle.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status-bundle-validation.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status-bundle-status.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status-bundle-status-bundle.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status-bundle-status-bundle-status.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status-bundle-status-bundle-status-validation.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-validation.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-validation.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-status.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-status-validation.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-validation.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-validation.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-validation.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-validation.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-validation.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status-bundle-status-validation.schema.json",
    "planningops/schemas/plain-python-compat-manifest-status-bundle-status-bundle-validation.schema.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-validation.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status-bundle.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status-bundle-validation.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status-bundle-status.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status-bundle-status-bundle.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status-bundle-status-bundle-status.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status-bundle-status-bundle-status-validation.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-validation.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-validation.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-status.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-status-validation.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-validation.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-validation.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-validation.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-validation.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-status-bundle-validation.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status-bundle-status-validation.json",
    "planningops/artifacts/validation/plain-python-compat-manifest-status-bundle-status-bundle-validation.json",
    "planningops/scripts/resolve_plain_python_compat_manifest.py",
    "planningops/scripts/resolve_plain_python_compat_manifest_status.py",
    "planningops/scripts/resolve_plain_python_compat_manifest_status_bundle_status.py",
    "planningops/scripts/validate_plain_python_compat_manifest.py",
    "planningops/scripts/validate_plain_python_compat_manifest_status.py",
    "planningops/scripts/validate_plain_python_compat_manifest_status_bundle.py",
    "planningops/scripts/validate_plain_python_compat_manifest_status_bundle_status.py",
    "planningops/scripts/validate_plain_python_compat_manifest_status_bundle_status_bundle.py",
    "planningops/scripts/validate_plain_python_compat_manifest_status_bundle_status_bundle_status.py",
    "planningops/scripts/validate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle.py",
    "planningops/scripts/validate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status.py",
    "planningops/scripts/validate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle.py",
    "planningops/scripts/validate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status.py",
    "planningops/scripts/validate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.py",
    "planningops/scripts/validate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status.py",
    "planningops/scripts/validate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.py",
    "planningops/scripts/validate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status.py",
    "planningops/scripts/resolve_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status.py",
    "planningops/scripts/resolve_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status.py",
    "planningops/scripts/validate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.py",
    "planningops/scripts/resolve_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status.py",
    "planningops/scripts/resolve_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status.py",
    "planningops/scripts/doctor_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.py",
    "planningops/scripts/gate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/doctor_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.py",
    "planningops/scripts/gate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/doctor_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle.py",
    "planningops/scripts/gate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/resolve_plain_python_compat_manifest_status_bundle_status_bundle_status.py",
    "planningops/scripts/doctor_plain_python_compat_manifest_status_bundle_status_bundle.py",
    "planningops/scripts/doctor_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle.py",
    "planningops/scripts/gate_plain_python_compat_manifest_status_bundle_status_bundle.sh",
    "planningops/scripts/gate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/doctor_plain_python_compat_manifest_status_bundle.py",
    "planningops/scripts/doctor_plain_python_compat_manifest.py",
    "planningops/scripts/gate_plain_python_compat_manifest_status_bundle.sh",
    "planningops/scripts/gate_plain_python_compat_manifest.sh",
    "planningops/scripts/test_validate_plain_python_compat_manifest_status_contract.sh",
    "planningops/scripts/test_validate_plain_python_compat_manifest_status_bundle_validation_contract.sh",
    "planningops/scripts/test_validate_plain_python_compat_manifest_status_bundle_status_contract.sh",
    "planningops/scripts/test_validate_plain_python_compat_manifest_status_bundle_status_validation_contract.sh",
    "planningops/scripts/test_validate_plain_python_compat_manifest_status_bundle_status_bundle_validation_contract.sh",
    "planningops/scripts/test_validate_plain_python_compat_manifest_status_bundle_status_bundle_status_contract.sh",
    "planningops/scripts/test_validate_plain_python_compat_manifest_status_bundle_status_bundle_status_validation_contract.sh",
    "planningops/scripts/test_validate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_validation_contract.sh",
    "planningops/scripts/test_validate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_contract.sh",
    "planningops/scripts/test_validate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_validation_contract.sh",
    "planningops/scripts/test_validate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_validation_contract.sh",
    "planningops/scripts/test_doctor_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/test_validate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_contract.sh",
    "planningops/scripts/test_validate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_validation_contract.sh",
    "planningops/scripts/test_resolve_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status.sh",
    "planningops/scripts/test_validate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_validation_contract.sh",
    "planningops/scripts/test_doctor_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/test_validate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_contract.sh",
    "planningops/scripts/test_validate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_validation_contract.sh",
    "planningops/scripts/test_resolve_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status.sh",
    "planningops/scripts/test_validate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_validation_contract.sh",
    "planningops/scripts/test_doctor_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/test_validate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_contract.sh",
    "planningops/scripts/test_validate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_validation_contract.sh",
    "planningops/scripts/test_resolve_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status.sh",
    "planningops/scripts/test_validate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_validation_contract.sh",
    "planningops/scripts/test_gate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/test_gate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/test_gate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/test_resolve_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle_status.sh",
    "planningops/scripts/test_resolve_plain_python_compat_manifest_status_bundle_status_bundle_status.sh",
    "planningops/scripts/test_doctor_plain_python_compat_manifest_status_bundle.sh",
    "planningops/scripts/test_gate_plain_python_compat_manifest_status_bundle.sh",
    "planningops/scripts/test_doctor_plain_python_compat_manifest_status_bundle_status_bundle.sh",
    "planningops/scripts/test_gate_plain_python_compat_manifest_status_bundle_status_bundle.sh",
    "planningops/scripts/test_doctor_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/test_gate_plain_python_compat_manifest_status_bundle_status_bundle_status_bundle.sh",
    "planningops/scripts/test_plain_python_compat_manifest_surface_inventory.sh",
    "planningops/scripts/test_resolve_plain_python_compat_manifest_status.sh",
    "planningops/scripts/test_resolve_plain_python_compat_manifest_status_bundle_status.sh",
    "planningops/scripts/test_cross_repo_plain_python_annotation_contract.sh",
    "planningops/scripts/test_cross_repo_plain_python_compat.sh",
    "planningops/scripts/test_runtime_stack_smoke_sequence_contract.sh",
    "from __future__ import annotations",
]

for snippet in required_contract_snippets:
    assert snippet in contract, f"missing contract snippet: {snippet}"

assert "plain-python-compat-manifest-contract.md" in contracts_readme, "contracts README missing plain python compat manifest contract"
PY

echo "plain python compat manifest contract doc ok"
